language: python
sudo: false
services:
  - docker

before_install:
  - uname -s
  - sudo apt-get update
  - sudo apt-get install -y jq

install:
  - pip install .
  - docker run trufflesuite/ganache-cli:latest --account="0x68d20faeaf9ac405bd32a98ba0835bbd14bbc4ffdedb60ea3a67329819b4d7a8,10"

script:
  - dymka version
  - dymka show
