language: python
sudo: false
services:
  - docker

before_install:
  - uname -s
  - sudo apt-get update
  - sudo apt-get install -y jq

env:
  WEB3_FROM=68d20faeaf9ac405bd32a98ba0835bbd14bbc4ffdedb60ea3a67329819b4d7a8 # test only key

install:
  - pip install .
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest --account="0x${WEB3_FROM},1"
  - sleep 10

script:
  - dymka version
  - dymka balance
