name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Pre
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Foundry Anvil
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        source ~/.bashrc
        more ~/.bashrc
        ls ~/.foundry/bin
        ~/.foundry/bin/foundryup
        nohup anvil --auto-impersonate &
        more nohup.out

    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run tests
      env:
        WEB3_FROM: ${{ secrets.TEST_PRIV }}
      run: |
        docker ps -a
        docker ps -aq
        docker logs $(docker ps -aq | head -1)
        tests/test.sh
